set_property SRC_FILE_INFO {cfile:C:/Users/jiangja5/hash_server/hash_server.srcs/constrs_1/new/SD_card.xdc rfile:../../../hash_server.srcs/constrs_1/new/SD_card.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS33} [get_ports SD_CD_0]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W20 IOSTANDARD LVCMOS33} [get_ports SD_CMD_0]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V19 IOSTANDARD LVCMOS33} [get_ports {SD_DAT_0[0]}]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T21 IOSTANDARD LVCMOS33} [get_ports {SD_DAT_0[1]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS33} [get_ports {SD_DAT_0[2]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports {SD_DAT_0[3]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVCMOS33} [get_ports SD_RESET_0]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports SD_SCK_0]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/sd_card_controller_0/inst/addr_ptr]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_reg[30]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_reg[29]}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_reg[31]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/sd_card_controller_0/m00_axi_araddr[27]} {design_1_i/sd_card_controller_0/m00_axi_araddr[28]} {design_1_i/sd_card_controller_0/m00_axi_araddr[29]} {design_1_i/sd_card_controller_0/m00_axi_araddr[30]}]]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/sdcont/recv_data[3]}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/sdcont/version[4]}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/SD_DAT[0]}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/sd_card_controller_0/resetn]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/sdcont/version[5]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/sd_card_controller_0/load]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/sdcont/recv_data[1]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/sdcont/recv_data[5]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/sd_card_controller_0/m00_axi_aresetn]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/sdcont/version[3]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/SD_DAT[3]}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/sdcont/version[0]}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/sd_card_controller_0/SD_CMD]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/sdcont/recv_data[0]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/sdcont/version[7]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/sd_card_controller_0/m00_axi_aclk]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/sdcont/version[1]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/sdcont/version[2]}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/sd_card_controller_0/SD_SCK]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/sdcont/recv_data[2]}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/sdcont/recv_data[7]}]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/sdcont/recv_data[4]}]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/sdcont/recv_data[6]}]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/sdcont/version[6]}]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_reg[0]}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_reg[1]}]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/inst/counter0[1]}]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets design_1_i/sd_card_controller_0/inst/byte_available_1]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/inst/counter0[0]}]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/inst/counter0[2]}]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets design_1_i/sd_card_controller_0/inst/data]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[9]}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[9]}]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[13]}]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[23]}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[24]}]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[19]}]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[24]}]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[29]}]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[2]}]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[10]}]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[0]}]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[11]}]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[22]}]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[26]}]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[11]}]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[1]}]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[19]}]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[20]}]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[14]}]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[22]}]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[25]}]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[30]}]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[2]}]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[6]}]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[4]}]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[7]}]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[8]}]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[17]}]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[20]}]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[23]}]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[28]}]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[13]}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[14]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[15]}]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[17]}]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[21]}]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[3]}]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[5]}]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[10]}]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[6]}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[27]}]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[4]}]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[26]}]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[5]}]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[16]}]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[16]}]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[12]}]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[7]}]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[12]}]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[18]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[3]}]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[8]}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[1]}]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[15]}]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[18]}]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[25]}]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[21]}]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {design_1_i/sd_card_controller_0/m00_axi_wdata[31]}]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list design_1_i/sd_card_controller_0/inst/byte_available]]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list design_1_i/sd_card_controller_0/inst/byte_available_1]]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets design_1_i/sd_card_controller_0/inst/sd_card_controller_v1_0_M00_AXI_inst/m00_axi_init_axi_txn]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/sd_card_controller_0/inst/addr_ptr_reg[0]} {design_1_i/sd_card_controller_0/inst/addr_ptr_reg[1]}]]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe21 [get_nets [list design_1_i/sd_card_controller_0/inst/signal]]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/sd_card_controller_0/inst/counter0[0]} {design_1_i/sd_card_controller_0/inst/counter0[1]} {design_1_i/sd_card_controller_0/inst/counter0[2]}]]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/sd_card_controller_0/inst/addr_ptr_reg[1]} {design_1_i/sd_card_controller_0/inst/addr_ptr_reg[29]} {design_1_i/sd_card_controller_0/inst/addr_ptr_reg[30]} {design_1_i/sd_card_controller_0/inst/addr_ptr_reg[31]}]]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list design_1_i/sd_card_controller_0/inst/data]]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list design_1_i/sd_card_controller_0/inst/sd_card_controller_v1_0_M00_AXI_inst/m00_axi_init_axi_txn]]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[11]}]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[9]}]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/state[2]}]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[30]}]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[16]}]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[19]}]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[1]}]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[31]}]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[17]}]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[23]}]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/sd_card_controller_0/inst/resetn]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[17]}]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[10]}]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[18]}]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/sd_card_controller_0/inst/rd]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[17]}]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/sd_card_controller_0/m00_axi_wvalid]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[27]}]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[13]}]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[28]}]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[31]}]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[11]}]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[22]}]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[9]}]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/sd_card_controller_0/inst/signal]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[6]}]
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[6]}]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/dout[7]}]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[2]}]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[2]}]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[27]}]
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/sd_card_controller_0/inst/rst]
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[0]}]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[12]}]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[1]}]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/sd_card_controller_0/inst/wr]
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[3]}]
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[11]}]
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[17]}]
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[12]}]
set_property src_info {type:XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[27]}]
set_property src_info {type:XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[14]}]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[7]}]
set_property src_info {type:XDC file:1 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[30]}]
set_property src_info {type:XDC file:1 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[19]}]
set_property src_info {type:XDC file:1 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/state[1]}]
set_property src_info {type:XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[5]}]
set_property src_info {type:XDC file:1 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/dout[2]}]
set_property src_info {type:XDC file:1 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[2]}]
set_property src_info {type:XDC file:1 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[5]}]
set_property src_info {type:XDC file:1 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[27]}]
set_property src_info {type:XDC file:1 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/sd_card_controller_0/m00_axi_bvalid]
set_property src_info {type:XDC file:1 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[15]}]
set_property src_info {type:XDC file:1 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[0]}]
set_property src_info {type:XDC file:1 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[3]}]
set_property src_info {type:XDC file:1 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/dout[1]}]
set_property src_info {type:XDC file:1 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[11]}]
set_property src_info {type:XDC file:1 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[22]}]
set_property src_info {type:XDC file:1 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[13]}]
set_property src_info {type:XDC file:1 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/dout[3]}]
set_property src_info {type:XDC file:1 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[3]}]
set_property src_info {type:XDC file:1 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[25]}]
set_property src_info {type:XDC file:1 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[18]}]
set_property src_info {type:XDC file:1 line:329 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[9]}]
set_property src_info {type:XDC file:1 line:330 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[23]}]
set_property src_info {type:XDC file:1 line:339 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/dout[4]}]
set_property src_info {type:XDC file:1 line:343 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[12]}]
set_property src_info {type:XDC file:1 line:349 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[16]}]
set_property src_info {type:XDC file:1 line:351 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[4]}]
set_property src_info {type:XDC file:1 line:354 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[9]}]
set_property src_info {type:XDC file:1 line:360 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[25]}]
set_property src_info {type:XDC file:1 line:361 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[22]}]
set_property src_info {type:XDC file:1 line:362 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[26]}]
set_property src_info {type:XDC file:1 line:363 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/sd_card_controller_0/inst/load]
set_property src_info {type:XDC file:1 line:372 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[0]}]
set_property src_info {type:XDC file:1 line:373 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[26]}]
set_property src_info {type:XDC file:1 line:377 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[19]}]
set_property src_info {type:XDC file:1 line:383 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[18]}]
set_property src_info {type:XDC file:1 line:392 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[24]}]
set_property src_info {type:XDC file:1 line:393 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[5]}]
set_property src_info {type:XDC file:1 line:397 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[10]}]
set_property src_info {type:XDC file:1 line:403 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/sd_card_controller_0/loaded]
set_property src_info {type:XDC file:1 line:404 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[15]}]
set_property src_info {type:XDC file:1 line:419 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/state[0]}]
set_property src_info {type:XDC file:1 line:420 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[13]}]
set_property src_info {type:XDC file:1 line:421 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/counter[1]}]
set_property src_info {type:XDC file:1 line:422 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[7]}]
set_property src_info {type:XDC file:1 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[20]}]
set_property src_info {type:XDC file:1 line:432 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[18]}]
set_property src_info {type:XDC file:1 line:433 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[14]}]
set_property src_info {type:XDC file:1 line:434 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/sd_card_controller_0/inst/ready]
set_property src_info {type:XDC file:1 line:442 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[8]}]
set_property src_info {type:XDC file:1 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[21]}]
set_property src_info {type:XDC file:1 line:444 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/sd_card_controller_0/m00_axi_rready]
set_property src_info {type:XDC file:1 line:445 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[10]}]
set_property src_info {type:XDC file:1 line:454 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[6]}]
set_property src_info {type:XDC file:1 line:455 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[23]}]
set_property src_info {type:XDC file:1 line:459 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[8]}]
set_property src_info {type:XDC file:1 line:465 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[28]}]
set_property src_info {type:XDC file:1 line:466 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/m00_axi_araddr[28]}]
set_property src_info {type:XDC file:1 line:473 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/state[4]}]
set_property src_info {type:XDC file:1 line:474 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[1]}]
set_property src_info {type:XDC file:1 line:475 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[29]}]
set_property src_info {type:XDC file:1 line:478 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[25]}]
set_property src_info {type:XDC file:1 line:484 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[12]}]
set_property src_info {type:XDC file:1 line:485 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/dout[5]}]
set_property src_info {type:XDC file:1 line:493 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[10]}]
set_property src_info {type:XDC file:1 line:494 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[0]}]
set_property src_info {type:XDC file:1 line:498 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[26]}]
set_property src_info {type:XDC file:1 line:504 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/sd_card_controller_0/m00_axi_bready]
set_property src_info {type:XDC file:1 line:505 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[11]}]
set_property src_info {type:XDC file:1 line:506 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[9]}]
set_property src_info {type:XDC file:1 line:515 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[19]}]
set_property src_info {type:XDC file:1 line:516 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/dout[6]}]
set_property src_info {type:XDC file:1 line:519 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[30]}]
set_property src_info {type:XDC file:1 line:525 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[26]}]
set_property src_info {type:XDC file:1 line:526 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[20]}]
set_property src_info {type:XDC file:1 line:529 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[29]}]
set_property src_info {type:XDC file:1 line:535 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[1]}]
set_property src_info {type:XDC file:1 line:536 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[25]}]
set_property src_info {type:XDC file:1 line:537 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[24]}]
set_property src_info {type:XDC file:1 line:540 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[28]}]
set_property src_info {type:XDC file:1 line:546 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[26]}]
set_property src_info {type:XDC file:1 line:547 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[24]}]
set_property src_info {type:XDC file:1 line:548 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[29]}]
set_property src_info {type:XDC file:1 line:549 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[16]}]
set_property src_info {type:XDC file:1 line:553 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[24]}]
set_property src_info {type:XDC file:1 line:559 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/counter[0]}]
set_property src_info {type:XDC file:1 line:560 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/m00_axi_araddr[27]}]
set_property src_info {type:XDC file:1 line:561 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[31]}]
set_property src_info {type:XDC file:1 line:562 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/sd_card_controller_0/inst/byte_available]
set_property src_info {type:XDC file:1 line:565 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[13]}]
set_property src_info {type:XDC file:1 line:571 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[14]}]
set_property src_info {type:XDC file:1 line:572 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[28]}]
set_property src_info {type:XDC file:1 line:576 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[15]}]
set_property src_info {type:XDC file:1 line:582 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[30]}]
set_property src_info {type:XDC file:1 line:590 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[7]}]
set_property src_info {type:XDC file:1 line:591 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[20]}]
set_property src_info {type:XDC file:1 line:592 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/sd_card_controller_0/m00_axi_rvalid]
set_property src_info {type:XDC file:1 line:600 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[29]}]
set_property src_info {type:XDC file:1 line:601 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[28]}]
set_property src_info {type:XDC file:1 line:602 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[30]}]
set_property src_info {type:XDC file:1 line:606 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[16]}]
set_property src_info {type:XDC file:1 line:612 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[19]}]
set_property src_info {type:XDC file:1 line:613 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/sd_card_controller_0/inst/ready_for_next_byte]
set_property src_info {type:XDC file:1 line:616 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[3]}]
set_property src_info {type:XDC file:1 line:622 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[2]}]
set_property src_info {type:XDC file:1 line:623 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[28]}]
set_property src_info {type:XDC file:1 line:631 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[15]}]
set_property src_info {type:XDC file:1 line:632 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[8]}]
set_property src_info {type:XDC file:1 line:635 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[21]}]
set_property src_info {type:XDC file:1 line:641 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/m00_axi_araddr[29]}]
set_property src_info {type:XDC file:1 line:642 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[4]}]
set_property src_info {type:XDC file:1 line:643 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[5]}]
set_property src_info {type:XDC file:1 line:652 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[8]}]
set_property src_info {type:XDC file:1 line:653 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[31]}]
set_property src_info {type:XDC file:1 line:654 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/sd_card_controller_0/m00_axi_awready]
set_property src_info {type:XDC file:1 line:655 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[18]}]
set_property src_info {type:XDC file:1 line:663 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[0]}]
set_property src_info {type:XDC file:1 line:664 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[15]}]
set_property src_info {type:XDC file:1 line:672 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[24]}]
set_property src_info {type:XDC file:1 line:673 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[6]}]
set_property src_info {type:XDC file:1 line:680 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[16]}]
set_property src_info {type:XDC file:1 line:681 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[22]}]
set_property src_info {type:XDC file:1 line:682 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/m00_axi_awaddr[27]}]
set_property src_info {type:XDC file:1 line:683 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[0]}]
set_property src_info {type:XDC file:1 line:684 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[14]}]
set_property src_info {type:XDC file:1 line:687 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/sd_card_controller_0/inst/sd_card_controller_v1_0_M00_AXI_inst/writes_done]
set_property src_info {type:XDC file:1 line:688 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[23]}]
set_property src_info {type:XDC file:1 line:694 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[1]}]
set_property src_info {type:XDC file:1 line:695 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[20]}]
set_property src_info {type:XDC file:1 line:696 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[21]}]
set_property src_info {type:XDC file:1 line:705 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/state[3]}]
set_property src_info {type:XDC file:1 line:706 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[31]}]
set_property src_info {type:XDC file:1 line:707 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/m00_axi_araddr[30]}]
set_property src_info {type:XDC file:1 line:710 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[4]}]
set_property src_info {type:XDC file:1 line:716 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[7]}]
set_property src_info {type:XDC file:1 line:717 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[17]}]
set_property src_info {type:XDC file:1 line:725 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[3]}]
set_property src_info {type:XDC file:1 line:726 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/dout[0]}]
set_property src_info {type:XDC file:1 line:727 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[22]}]
set_property src_info {type:XDC file:1 line:736 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[29]}]
set_property src_info {type:XDC file:1 line:739 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[14]}]
set_property src_info {type:XDC file:1 line:745 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/sd_card_controller_0/m00_axi_awvalid]
set_property src_info {type:XDC file:1 line:746 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[21]}]
set_property src_info {type:XDC file:1 line:747 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[27]}]
set_property src_info {type:XDC file:1 line:748 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[6]}]
set_property src_info {type:XDC file:1 line:756 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[4]}]
set_property src_info {type:XDC file:1 line:757 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[21]}]
set_property src_info {type:XDC file:1 line:758 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[8]}]
set_property src_info {type:XDC file:1 line:761 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[5]}]
set_property src_info {type:XDC file:1 line:767 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[4]}]
set_property src_info {type:XDC file:1 line:768 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[29]}]
set_property src_info {type:XDC file:1 line:770 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[2]}]
set_property src_info {type:XDC file:1 line:776 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[23]}]
set_property src_info {type:XDC file:1 line:777 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/data[10]}]
set_property src_info {type:XDC file:1 line:778 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[13]}]
set_property src_info {type:XDC file:1 line:786 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/address[25]}]
set_property src_info {type:XDC file:1 line:787 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/addr_ptr_0[20]}]
set_property src_info {type:XDC file:1 line:788 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_awaddr[12]}]
set_property src_info {type:XDC file:1 line:792 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {design_1_i/sd_card_controller_0/inst/m00_axi_wdata[7]}]
set_property src_info {type:XDC file:1 line:798 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets design_1_i/sd_card_controller_0/m00_axi_wready]
