webtalk_init -webtalk_dir C:/ece532/proj/hash_func_pipe/hash_func_pipe.sim/sim_1/behav/xsim/xsim.dir/md5_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Feb 20 13:54:05 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2d8ce7a9-6f84-4f9d-89b3-5fe25177cca9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3f86cf27619c4526a29ec61aadf0ada9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "20" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 4700U with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1996 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "896 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7764_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3983877280 -regid "" -xml C:/ece532/proj/hash_func_pipe/hash_func_pipe.sim/sim_1/behav/xsim/xsim.dir/md5_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/ece532/proj/hash_func_pipe/hash_func_pipe.sim/sim_1/behav/xsim/xsim.dir/md5_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/ece532/proj/hash_func_pipe/hash_func_pipe.sim/sim_1/behav/xsim/xsim.dir/md5_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
