set_property MARK_DEBUG true [get_nets {design_1_i/spam_detection_infer_0/inst/cnt[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/spam_detection_infer_0/inst/cnt[1]}]

set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/data_count[3]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/data_count[5]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/data_count[8]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[4]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[20]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[13]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[17]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[22]}]
set_property MARK_DEBUG false [get_nets design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/rd_en]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[21]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/data_count[2]}]
set_property MARK_DEBUG false [get_nets design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/empty]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[31]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[10]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[16]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[18]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[3]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[19]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[23]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[21]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[27]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[0]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[12]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[22]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[6]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[7]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[15]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[18]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[25]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[26]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[1]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[3]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[28]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[0]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[8]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[9]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[14]}]
set_property MARK_DEBUG false [get_nets design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/<const0>]
set_property MARK_DEBUG false [get_nets design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/full]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[28]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[31]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[8]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[2]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[15]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[5]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[7]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[17]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[10]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[16]}]
set_property MARK_DEBUG false [get_nets design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/clk]
set_property MARK_DEBUG false [get_nets design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/wr_en]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[5]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/data_count[6]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[9]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/data_count[0]}]
set_property MARK_DEBUG false [get_nets design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/srst]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[4]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/data_count[7]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[11]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[20]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[29]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[24]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/data_count[4]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/data_count[1]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[12]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[14]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[23]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[25]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[13]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[1]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[30]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[29]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[30]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[6]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[2]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[11]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[24]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/din[27]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[19]}]
set_property MARK_DEBUG false [get_nets {design_1_i/spam_detection_infer_0/inst/spam_prob_buffer/dout[26]}]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/clk_wiz_1/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/spam_detection_infer_0/inst/fifo_dout[0]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[1]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[2]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[3]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[4]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[5]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[6]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[7]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[8]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[9]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[10]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[11]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[12]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[13]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[14]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[15]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[16]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[17]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[18]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[19]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[20]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[21]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[22]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[23]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[24]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[25]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[26]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[27]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[28]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[29]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[30]} {design_1_i/spam_detection_infer_0/inst/fifo_dout[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 2 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/spam_detection_infer_0/inst/cnt[0]} {design_1_i/spam_detection_infer_0/inst/cnt[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 2 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/spam_detection_infer_0/inst/cnt_1[0]} {design_1_i/spam_detection_infer_0/inst/cnt_1[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/spam_detection_infer_0/inst/spam_opb[0]} {design_1_i/spam_detection_infer_0/inst/spam_opb[1]} {design_1_i/spam_detection_infer_0/inst/spam_opb[2]} {design_1_i/spam_detection_infer_0/inst/spam_opb[3]} {design_1_i/spam_detection_infer_0/inst/spam_opb[4]} {design_1_i/spam_detection_infer_0/inst/spam_opb[5]} {design_1_i/spam_detection_infer_0/inst/spam_opb[6]} {design_1_i/spam_detection_infer_0/inst/spam_opb[7]} {design_1_i/spam_detection_infer_0/inst/spam_opb[8]} {design_1_i/spam_detection_infer_0/inst/spam_opb[9]} {design_1_i/spam_detection_infer_0/inst/spam_opb[10]} {design_1_i/spam_detection_infer_0/inst/spam_opb[11]} {design_1_i/spam_detection_infer_0/inst/spam_opb[12]} {design_1_i/spam_detection_infer_0/inst/spam_opb[13]} {design_1_i/spam_detection_infer_0/inst/spam_opb[14]} {design_1_i/spam_detection_infer_0/inst/spam_opb[15]} {design_1_i/spam_detection_infer_0/inst/spam_opb[16]} {design_1_i/spam_detection_infer_0/inst/spam_opb[17]} {design_1_i/spam_detection_infer_0/inst/spam_opb[18]} {design_1_i/spam_detection_infer_0/inst/spam_opb[19]} {design_1_i/spam_detection_infer_0/inst/spam_opb[20]} {design_1_i/spam_detection_infer_0/inst/spam_opb[21]} {design_1_i/spam_detection_infer_0/inst/spam_opb[22]} {design_1_i/spam_detection_infer_0/inst/spam_opb[23]} {design_1_i/spam_detection_infer_0/inst/spam_opb[24]} {design_1_i/spam_detection_infer_0/inst/spam_opb[25]} {design_1_i/spam_detection_infer_0/inst/spam_opb[26]} {design_1_i/spam_detection_infer_0/inst/spam_opb[27]} {design_1_i/spam_detection_infer_0/inst/spam_opb[28]} {design_1_i/spam_detection_infer_0/inst/spam_opb[29]} {design_1_i/spam_detection_infer_0/inst/spam_opb[30]} {design_1_i/spam_detection_infer_0/inst/spam_opb[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 9 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/spam_detection_infer_0/inst/fifo_count[0]} {design_1_i/spam_detection_infer_0/inst/fifo_count[1]} {design_1_i/spam_detection_infer_0/inst/fifo_count[2]} {design_1_i/spam_detection_infer_0/inst/fifo_count[3]} {design_1_i/spam_detection_infer_0/inst/fifo_count[4]} {design_1_i/spam_detection_infer_0/inst/fifo_count[5]} {design_1_i/spam_detection_infer_0/inst/fifo_count[6]} {design_1_i/spam_detection_infer_0/inst/fifo_count[7]} {design_1_i/spam_detection_infer_0/inst/fifo_count[8]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/spam_detection_infer_0/inst/spam_opa[0]} {design_1_i/spam_detection_infer_0/inst/spam_opa[1]} {design_1_i/spam_detection_infer_0/inst/spam_opa[2]} {design_1_i/spam_detection_infer_0/inst/spam_opa[3]} {design_1_i/spam_detection_infer_0/inst/spam_opa[4]} {design_1_i/spam_detection_infer_0/inst/spam_opa[5]} {design_1_i/spam_detection_infer_0/inst/spam_opa[6]} {design_1_i/spam_detection_infer_0/inst/spam_opa[7]} {design_1_i/spam_detection_infer_0/inst/spam_opa[8]} {design_1_i/spam_detection_infer_0/inst/spam_opa[9]} {design_1_i/spam_detection_infer_0/inst/spam_opa[10]} {design_1_i/spam_detection_infer_0/inst/spam_opa[11]} {design_1_i/spam_detection_infer_0/inst/spam_opa[12]} {design_1_i/spam_detection_infer_0/inst/spam_opa[13]} {design_1_i/spam_detection_infer_0/inst/spam_opa[14]} {design_1_i/spam_detection_infer_0/inst/spam_opa[15]} {design_1_i/spam_detection_infer_0/inst/spam_opa[16]} {design_1_i/spam_detection_infer_0/inst/spam_opa[17]} {design_1_i/spam_detection_infer_0/inst/spam_opa[18]} {design_1_i/spam_detection_infer_0/inst/spam_opa[19]} {design_1_i/spam_detection_infer_0/inst/spam_opa[20]} {design_1_i/spam_detection_infer_0/inst/spam_opa[21]} {design_1_i/spam_detection_infer_0/inst/spam_opa[22]} {design_1_i/spam_detection_infer_0/inst/spam_opa[23]} {design_1_i/spam_detection_infer_0/inst/spam_opa[24]} {design_1_i/spam_detection_infer_0/inst/spam_opa[25]} {design_1_i/spam_detection_infer_0/inst/spam_opa[26]} {design_1_i/spam_detection_infer_0/inst/spam_opa[27]} {design_1_i/spam_detection_infer_0/inst/spam_opa[28]} {design_1_i/spam_detection_infer_0/inst/spam_opa[29]} {design_1_i/spam_detection_infer_0/inst/spam_opa[30]} {design_1_i/spam_detection_infer_0/inst/spam_opa[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_1_i/spam_detection_infer_0/inst/fifo_din[0]} {design_1_i/spam_detection_infer_0/inst/fifo_din[1]} {design_1_i/spam_detection_infer_0/inst/fifo_din[2]} {design_1_i/spam_detection_infer_0/inst/fifo_din[3]} {design_1_i/spam_detection_infer_0/inst/fifo_din[4]} {design_1_i/spam_detection_infer_0/inst/fifo_din[5]} {design_1_i/spam_detection_infer_0/inst/fifo_din[6]} {design_1_i/spam_detection_infer_0/inst/fifo_din[7]} {design_1_i/spam_detection_infer_0/inst/fifo_din[8]} {design_1_i/spam_detection_infer_0/inst/fifo_din[9]} {design_1_i/spam_detection_infer_0/inst/fifo_din[10]} {design_1_i/spam_detection_infer_0/inst/fifo_din[11]} {design_1_i/spam_detection_infer_0/inst/fifo_din[12]} {design_1_i/spam_detection_infer_0/inst/fifo_din[13]} {design_1_i/spam_detection_infer_0/inst/fifo_din[14]} {design_1_i/spam_detection_infer_0/inst/fifo_din[15]} {design_1_i/spam_detection_infer_0/inst/fifo_din[16]} {design_1_i/spam_detection_infer_0/inst/fifo_din[17]} {design_1_i/spam_detection_infer_0/inst/fifo_din[18]} {design_1_i/spam_detection_infer_0/inst/fifo_din[19]} {design_1_i/spam_detection_infer_0/inst/fifo_din[20]} {design_1_i/spam_detection_infer_0/inst/fifo_din[21]} {design_1_i/spam_detection_infer_0/inst/fifo_din[22]} {design_1_i/spam_detection_infer_0/inst/fifo_din[23]} {design_1_i/spam_detection_infer_0/inst/fifo_din[24]} {design_1_i/spam_detection_infer_0/inst/fifo_din[25]} {design_1_i/spam_detection_infer_0/inst/fifo_din[26]} {design_1_i/spam_detection_infer_0/inst/fifo_din[27]} {design_1_i/spam_detection_infer_0/inst/fifo_din[28]} {design_1_i/spam_detection_infer_0/inst/fifo_din[29]} {design_1_i/spam_detection_infer_0/inst/fifo_din[30]} {design_1_i/spam_detection_infer_0/inst/fifo_din[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 32 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {design_1_i/spam_detection_infer_0/inst/spam_out[0]} {design_1_i/spam_detection_infer_0/inst/spam_out[1]} {design_1_i/spam_detection_infer_0/inst/spam_out[2]} {design_1_i/spam_detection_infer_0/inst/spam_out[3]} {design_1_i/spam_detection_infer_0/inst/spam_out[4]} {design_1_i/spam_detection_infer_0/inst/spam_out[5]} {design_1_i/spam_detection_infer_0/inst/spam_out[6]} {design_1_i/spam_detection_infer_0/inst/spam_out[7]} {design_1_i/spam_detection_infer_0/inst/spam_out[8]} {design_1_i/spam_detection_infer_0/inst/spam_out[9]} {design_1_i/spam_detection_infer_0/inst/spam_out[10]} {design_1_i/spam_detection_infer_0/inst/spam_out[11]} {design_1_i/spam_detection_infer_0/inst/spam_out[12]} {design_1_i/spam_detection_infer_0/inst/spam_out[13]} {design_1_i/spam_detection_infer_0/inst/spam_out[14]} {design_1_i/spam_detection_infer_0/inst/spam_out[15]} {design_1_i/spam_detection_infer_0/inst/spam_out[16]} {design_1_i/spam_detection_infer_0/inst/spam_out[17]} {design_1_i/spam_detection_infer_0/inst/spam_out[18]} {design_1_i/spam_detection_infer_0/inst/spam_out[19]} {design_1_i/spam_detection_infer_0/inst/spam_out[20]} {design_1_i/spam_detection_infer_0/inst/spam_out[21]} {design_1_i/spam_detection_infer_0/inst/spam_out[22]} {design_1_i/spam_detection_infer_0/inst/spam_out[23]} {design_1_i/spam_detection_infer_0/inst/spam_out[24]} {design_1_i/spam_detection_infer_0/inst/spam_out[25]} {design_1_i/spam_detection_infer_0/inst/spam_out[26]} {design_1_i/spam_detection_infer_0/inst/spam_out[27]} {design_1_i/spam_detection_infer_0/inst/spam_out[28]} {design_1_i/spam_detection_infer_0/inst/spam_out[29]} {design_1_i/spam_detection_infer_0/inst/spam_out[30]} {design_1_i/spam_detection_infer_0/inst/spam_out[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 32 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {design_1_i/spam_detection_infer_0/inst/spam_result[0]} {design_1_i/spam_detection_infer_0/inst/spam_result[1]} {design_1_i/spam_detection_infer_0/inst/spam_result[2]} {design_1_i/spam_detection_infer_0/inst/spam_result[3]} {design_1_i/spam_detection_infer_0/inst/spam_result[4]} {design_1_i/spam_detection_infer_0/inst/spam_result[5]} {design_1_i/spam_detection_infer_0/inst/spam_result[6]} {design_1_i/spam_detection_infer_0/inst/spam_result[7]} {design_1_i/spam_detection_infer_0/inst/spam_result[8]} {design_1_i/spam_detection_infer_0/inst/spam_result[9]} {design_1_i/spam_detection_infer_0/inst/spam_result[10]} {design_1_i/spam_detection_infer_0/inst/spam_result[11]} {design_1_i/spam_detection_infer_0/inst/spam_result[12]} {design_1_i/spam_detection_infer_0/inst/spam_result[13]} {design_1_i/spam_detection_infer_0/inst/spam_result[14]} {design_1_i/spam_detection_infer_0/inst/spam_result[15]} {design_1_i/spam_detection_infer_0/inst/spam_result[16]} {design_1_i/spam_detection_infer_0/inst/spam_result[17]} {design_1_i/spam_detection_infer_0/inst/spam_result[18]} {design_1_i/spam_detection_infer_0/inst/spam_result[19]} {design_1_i/spam_detection_infer_0/inst/spam_result[20]} {design_1_i/spam_detection_infer_0/inst/spam_result[21]} {design_1_i/spam_detection_infer_0/inst/spam_result[22]} {design_1_i/spam_detection_infer_0/inst/spam_result[23]} {design_1_i/spam_detection_infer_0/inst/spam_result[24]} {design_1_i/spam_detection_infer_0/inst/spam_result[25]} {design_1_i/spam_detection_infer_0/inst/spam_result[26]} {design_1_i/spam_detection_infer_0/inst/spam_result[27]} {design_1_i/spam_detection_infer_0/inst/spam_result[28]} {design_1_i/spam_detection_infer_0/inst/spam_result[29]} {design_1_i/spam_detection_infer_0/inst/spam_result[30]} {design_1_i/spam_detection_infer_0/inst/spam_result[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list design_1_i/spam_detection_infer_0/inst/fifo_almost_empty]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list design_1_i/spam_detection_infer_0/inst/fifo_empty]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list design_1_i/spam_detection_infer_0/inst/fifo_full]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list design_1_i/spam_detection_infer_0/inst/fifo_rd_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list design_1_i/spam_detection_infer_0/inst/fifo_wr_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list design_1_i/spam_detection_infer_0/inst/fpu_out_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list design_1_i/spam_detection_infer_0/inst/spam_fpu_done]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
