webtalk_init -webtalk_dir C:/Users/Owner/ECE532/project/Client_FPGA/Feb_27_proj/ip_repo/edit_spam_detection_inference_v1_0.sim/sim_1/behav/xsim/xsim.dir/spam_detection_controller_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Mar 16 18:40:21 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2489853" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d876315c-21ee-41c3-9fc3-b5b1eda3ce83" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "980446bd1445489ba176176171143e54" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "70" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8184_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1017579541 -regid "" -xml C:/Users/Owner/ECE532/project/Client_FPGA/Feb_27_proj/ip_repo/edit_spam_detection_inference_v1_0.sim/sim_1/behav/xsim/xsim.dir/spam_detection_controller_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Owner/ECE532/project/Client_FPGA/Feb_27_proj/ip_repo/edit_spam_detection_inference_v1_0.sim/sim_1/behav/xsim/xsim.dir/spam_detection_controller_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Owner/ECE532/project/Client_FPGA/Feb_27_proj/ip_repo/edit_spam_detection_inference_v1_0.sim/sim_1/behav/xsim/xsim.dir/spam_detection_controller_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
