# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Owner/ECE532/project/Client_FPGA/Feb_27_proj/client_proj/client_proj.srcs/sources_1/bd/design_1/ip/design_1_spam_detection_infer_0_0/design_1_spam_detection_infer_0_0.xci
# IP: The module: 'design_1_spam_detection_infer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Owner/ECE532/project/Client_FPGA/Feb_27_proj/client_proj/client_proj.srcs/sources_1/bd/design_1/ip/design_1_spam_detection_infer_0_0/src/fifo_generator_0/fifo_generator_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: c:/Users/Owner/ECE532/project/Client_FPGA/Feb_27_proj/client_proj/client_proj.srcs/sources_1/bd/design_1/ip/design_1_spam_detection_infer_0_0/src/fifo_generator_0/fifo_generator_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: C:/Users/Owner/ECE532/project/Client_FPGA/Feb_27_proj/client_proj/client_proj.srcs/sources_1/bd/design_1/ip/design_1_spam_detection_infer_0_0/design_1_spam_detection_infer_0_0.xci
# IP: The module: 'design_1_spam_detection_infer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Owner/ECE532/project/Client_FPGA/Feb_27_proj/client_proj/client_proj.srcs/sources_1/bd/design_1/ip/design_1_spam_detection_infer_0_0/src/fifo_generator_0/fifo_generator_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: c:/Users/Owner/ECE532/project/Client_FPGA/Feb_27_proj/client_proj/client_proj.srcs/sources_1/bd/design_1/ip/design_1_spam_detection_infer_0_0/src/fifo_generator_0/fifo_generator_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
